---
# copy all scrapers and api related files (.py and .txt) to remote server

- name: ensure remote root dir exists
  file: path={{ remote_root_dir }} state=directory
  become: true


- name: create datetime release string
  local_action: shell date +%Y%m%d_%H%M%S
  register: release_datetime
  run_once: true


- name: ensure remote backup dir exists
  file: path={{ remote_root_dir }}/{{ remote_backup_dir }}/{{ app_name }}/{{ release_datetime.stdout }} state=directory
  become: true


- name: compress files local django files to local zip file
  local_action: shell zip -r ../files/{{ app_name }}.zip ../../api ../../scrapers


- name: unzip files to remote side
  unarchive: src=../files/{{ app_name }}.zip dest={{ remote_root_dir }}/{{ remote_backup_dir }}/{{ app_name }}/{{ release_datetime.stdout }} remote_src=no mode=775
  become: true
  ignore_errors: yes
  no_log: true


- name: create symbolic link from remote backup dir to remote app dir
  file: path={{ remote_root_dir }}/{{ app_name }} src={{ remote_root_dir }}/{{ remote_backup_dir }}/{{ app_name }}/{{ release_datetime.stdout }} state=link
  become: true


- name: check current server indicator exists
  stat: path={{ remote_root_dir }}/{{ remote_backup_dir }}/{{ app_name }}/server.current
  register: current_server
  become: true


- name: move current server indicator to backup
  shell: mv server.current server.backup chdir={{ remote_root_dir }}/{{ remote_backup_dir }}/{{ app_name }}
  when: current_server.stat.exists
  become: true


- name: create new current server indicator
  copy: content="{{ release_datetime.stdout }}" dest={{ remote_root_dir }}/{{ remote_backup_dir }}/{{ app_name }}/server.current
  become: true