name: Presubmit

on: [push]

jobs:
  build-and-test-front-end:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
        working-directory: www
      - name: Build
        run: yarn build
        working-directory: www
      - name: Run tests
        run: yarn test
        working-directory: www

  test-shared:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        - name: Install dependencies
          run: yarn
          working-directory: shared
        - name: Run tests
          run: yarn test
          working-directory: shared

  build-cloud-functions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and build
        run: |
          cd functions
          yarn
          yarn build
