name: Presubmit

on: [push]

jobs:
  front_end:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
        working-directory: www
      - name: Build
        run: yarn build
        working-directory: www
      - name: Run tests
        run: yarn test
        working-directory: www

  shared:
    runs-on: ubuntu-latest

    env:
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_NAME: db
      DB_HOST: cluster0.vz30l.mongodb.net

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
        working-directory: shared
      - name: Run tests
        run: yarn test
        working-directory: shared

  functions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
        working-directory: functions
      - name: Build
        run: yarn build
        working-directory: functions
